### ISSUE TITLE
无法下载课程视频

### ISSUE THREAD

**Issue by Gwzlchn** [TheBetterKong/UCAS_Sep#2]
```sh
*****************************************************************
请选择功能（0.课件下载 1.课程视频下载）：1
请选择下载课程的课程编号：6
# 所选课程为： 计算机算法设计与分析20-21秋季
**********************************************
开始下载：
进入计算机算法设计与分析20-21秋季课程视频页面中……
请选择下载的视频类型（0.课程视频 1.直播视频）：0
获取资源列表，寻找资源链接……
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/docker_test/course/UCAS_Sep/UCAS_Sep.py in <module>
    363         print("**********************************************")
    364         print('开始下载：')
--> 365         summary = download_course_sp(courseID, courseInfo, session)
    366         if summary != [] :
    367             print("**********************************************")

~/docker_test/course/UCAS_Sep/UCAS_Sep.py in download_course_sp(courseID, courseInfo, session)
    221     url = h_bs.find_all(title="课程视频 - 课程视频")[0].get("href")
    222     print('进入%s课程视频页面中……' % currentClassName)
--> 223     downloadfile = getClass_sp(currentClassName, url, session)
    224     #print(downloadfile)
    225     if downloadfile != []:

~/docker_test/course/UCAS_Sep/UCAS_Sep.py in getClass_sp(currentClass, url, session)
    263                 Url = 'https://course.ucas.ac.cn/portal/site/173754/tool/999d7ddb-4ec6-465f-8eaa-ac2ba8785d55/video/play?id='+id+'&type=u'
    264                 htl = session.get(Url)
--> 265                 spUrl = re.search('<source src="(.*?)" type="application/x-mpegURL">', htl.text, re.S).groups()[0]
    266                 spName1 = list.a['title'].replace(':','-')
    267                 spName = spName1.replace(' ','-')

AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by TheBetterKong** [comment]
你上一下你的教务系统，看看《计算机算法设计与分析20-21秋季》这门课“课程视频”和“直播视频”栏目下有没有视频

**Comment by Gwzlchn** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    您好~我刚才看了一下，应该是有课程视频的，见下截图：（课程编号：081203M04001H）
        
            
        
    
    
        
            
        
    
    
        
        

        
    

    在2020年10月25日 21:45，TheBetterKong<notifications@github.com> 写道： 




你上一下你的教务系统，看看《计算机算法设计与分析20-21秋季》这门课“课程视频”和“直播视频”栏目下有没有视频

**Comment by TheBetterKong** [comment]
我这看不到你的图呀.....你给我邮箱发一下你qq吧，qq交流

**Comment by Gwzlchn** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        QQ: 499371329
        
    
        
            
        
    
    
        
        

        
    

    在2020年10月25日 21:52，wangzelin20s<wangzelin20s@ict.ac.cn> 写道： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    您好~我刚才看了一下，应该是有课程视频的，见下截图：（课程编号：081203M04001H）
        
            
        
    
    
        
            
        
    
    
        
        

        
    

    在2020年10月25日 21:45，TheBetterKong<notifications@github.com> 写道： 




你上一下你的教务系统，看看《计算机算法设计与分析20-21秋季》这门课“课程视频”和“直播视频”栏目下有没有视频
